### PR TITLE
Added Q6 Medium solutions

### PR DESCRIPTION
**Pull request by eest12**

### CODE REVIEW

**Comment by emmanuelcodev** [comment]
I'm currently reviewing these solutions.

**Review by algorithms-21 — CHANGES_REQUESTED** [review]
Wow. Your solutions are pretty amazing. Comments are extremely helpful. I love how you integrated partial selection sort and used both a smallest and largest algorithm to reduce unnecessary work. It was beautiful. Both algorithms work and the time complexity is fine. There is only one comment that I was not sure if it was a typo. It was for your second algorithm. 

You wrote   
Time complexity: O(kn), worst case O(n^2) when k=n/2

Did you mean when k= n? Let me know if I am misreading this. I'll approve your code after.

**Comment by eest12** [comment]
Thanks for the feedback! My reasoning for k=n/2 was that the worst case scenario happens when k is half of n, since that's the largest value that cannot be reduced. When k=n, this is essentially the same as k=1. So the worst time is O(kn) = O((n/2)*n) = O((n^2)/2) = O(n^2).

**Comment by algorithms-21** [comment]
You are absolutely correct. Thanks for clearing that up!

**Pull request merged**
